[package]
name = "stream"
version = "0.0.5"
description = "Stream sender and receiver libraries"
repository = "https://github.com/research-ag/stream"
keywords = [ "sender", "receiver", "batch", "concurrent", "order" ]
license = "Apache-2.0"

[dependencies]
core = "2.0.0"
swb = "1.2.2"
promtracker = "0.7.0"

[dev-dependencies]
async-test = "0.0.2"

[requirements]
moc = "1.0.0"

[toolchain]
moc = "1.1.0"
